export const data = {
    products: [
        {
            // _id: '1',
            name: 'Macbook Air',
            itemId: 'Macbook Air 13',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '1365',
            brand: 'Apple',
            modelName: 'Macbook Air M1 13-inches 2020',
            operatingSystem: 'Mac Os',
            graphicCard: 'Integrated',
            rating: 5,
            numberOfReviews: 10,
            inStock: 0,
            description: '2020 Apple MacBook Air Laptop: Apple M1 Chip, 13″ Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID.'
        }, 
        {
            // _id: '2',
            name: 'Zenbook Flip S13',
            itemId: 'Zenbook Flip S13',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '2225',
            brand: 'Asus',
            modelName: 'ASUS ZenBook Flip S13',
            operatingSystem: 'Window 10 Pro',
            graphicCard: 'NVIDIA® GeForce RTX™ 3050 Ti 4GB GDDR6',
            rating: 4.5,
            numberOfReviews: 3,
            inStock: 20,
            description: 'ASUS ZenBook Flip S13 OLED Slim Laptop, 13.3” 4K OLED Touch, Intel Evo Platform Core i7-1165G7, 16GB RAM, 1TB SSD, Thunderbolt 4, TPM, Windows 11 Pro, AI Noise-Cancellation, Jade Black UX371EA-XH76T'
        },
        {
            // _id: '3',
            name: 'Macbook Pro',
            itemId: 'Macbook Pro 15',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '1595',
            brand: 'Apple',
            modelName: 'Macbook Air M1 13-inches 2020',
            operatingSystem: 'Mac Os',
            graphicCard: 'Integrated',
            rating: 4,
            numberOfReviews: 5,
            inStock: 20,
            description: '2020 Apple MacBook Air Laptop: Apple M1 Chip, 13″ Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Space Grey'
        },
        {
            // _id: '4',
            name: 'Dell Xps',
            itemId: 'Dell Xps',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '2165',
            brand: 'Apple',
            modelName: 'Macbook Air M1 13-inches 2020',
            operatingSystem: 'Mac Os',
            graphicCard: 'Integrated',
            rating: 3.5,
            numberOfReviews: 6,
            inStock: 20,
            description: '2020 Apple MacBook Air Laptop: Apple M1 Chip, 13″ Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Space Grey'
        },
        {
            // _id: '5',
            name: 'Macbook Pro',
            itemId: 'Macbook Pro 13',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '1765',
            brand: 'Apple',
            modelName: 'Macbook Pro M2 13-inches 2022',
            operatingSystem: 'Mac Os',
            graphicCard: 'Integrated',
            rating: 5,
            numberOfReviews: 1,
            inStock: 0,
            description: '2020 Apple MacBook Air Laptop: Apple M1 Chip, 13″ Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Space Grey'
        },
        {
            // _id: '6',
            name: 'Dell Latitude',
            itemId: 'Dell Latitude',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '1765',
            brand: 'Apple',
            modelName: 'Macbook Pro M2 13-inches 2022',
            operatingSystem: 'Mac Os',
            graphicCard: 'Integrated',
            rating: 5,
            numberOfReviews: 1,
            inStock: 3,
            description: '2020 Apple MacBook Air Laptop: Apple M1 Chip, 13″ Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Space Grey'
        },
        {
            // _id: '7',
            name: 'Dell Inspiron',
            itemId: 'Dell Inspiron',
            category: 'Laptops',
            image: '/images/MacAirM1.png',
            price: '1765',
            brand: 'Apple',
            modelName: 'Macbook Pro M2 13-inches 2022',
            operatingSystem: 'Mac Os',
            graphicCard: 'Integrated',
            rating: 5,
            numberOfReviews: 1,
            inStock: 6,
            description: '2020 Apple MacBook Air Laptop: Apple M1 Chip, 13″ Retina Display, 8GB RAM, 256GB SSD Storage, Backlit Keyboard, FaceTime HD Camera, Touch ID. Works with iPhone/iPad; Space Grey'
        },
    ]
}